; Firmware Volumefy per ESP32-C3 SuperMini
; Profilo PlatformIO usato dal progetto locale originale.
[env:esp32-c3-devkitm-1]
platform = espressif32@6.5.0
board = esp32-c3-devkitm-1
framework = arduino
board_build.mcu = esp32c3
lib_deps =
    h2zero/NimBLE-Arduino@1.4.3
    https://github.com/T-vK/ESP32-BLE-Keyboard.git#b7aaf9bb711a04216e4417f1e2a6b0ee0eaeaf66
build_flags =
    -D USE_NIMBLE
